import React, { useEffect, useRef, useState } from 'react';

const Reveal = ({children, delay=0, className=''}:{children:React.ReactNode;delay?:number;className?:string}) => {
  const ref = useRef<HTMLDivElement>(null);
  const [show,setShow] = useState(false);
  useEffect(()=>{
    const el=ref.current;
    if(!el) return;
    const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShow(true);io.disconnect();}},{threshold:.12});
    io.observe(el);
    return()=>io.disconnect();
  },[]);
  return <div ref={ref} className={`reveal ${show?'show':''} ${className}`} style={{transitionDelay:`${delay}ms`}}>{children}</div>;
};

const Label=({children}:{children:React.ReactNode})=><div className="label"><span/>{children}</div>;

export default function App(){
return <div className="site" id="topo">
<style>{`
:root{--ink:#0b0b0c;--ink2:#121213;--cream:#efe7da;--paper:#f8f4ec;--gold:#d7ad60;--gold2:#a87b33;--muted:#b8b0a4;--line:#302d27}
*{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;background:var(--ink);color:#f6f1e8;font-family:Inter,Arial,sans-serif;overflow-x:hidden}.site{min-height:100vh}.wrap{width:min(1160px,calc(100% - 40px));margin:auto} h1,h2,h3,.serif{font-family:Georgia,'Times New Roman',serif}.gold{color:var(--gold)}
.top{position:sticky;top:0;z-index:60;background:rgba(11,11,12,.82);backdrop-filter:blur(16px);border-bottom:1px solid rgba(215,173,96,.12)}.top-in{height:70px;display:flex;align-items:center;justify-content:space-between;gap:22px}.brand{display:flex;align-items:center;gap:12px;font-family:Georgia,serif;font-size:18px;font-weight:700}.brand-mark{width:34px;height:34px;border:1px solid var(--gold);display:grid;place-items:center;color:var(--gold);font-size:14px}.nav{display:flex;gap:24px}.nav a,.text-link{color:#d8d0c3;text-decoration:none;font-size:13px}.nav a:hover,.text-link:hover{color:var(--gold)}
.btn,.top-btn{position:relative;overflow:hidden;background:linear-gradient(180deg,#e3bf78,#c69647);color:#111;text-decoration:none;font-weight:900;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;transition:.28s ease;box-shadow:0 10px 30px rgba(215,173,96,.12)}.btn{padding:17px 25px}.top-btn{padding:11px 18px;font-size:13px}.btn:after,.top-btn:after{content:'';position:absolute;top:-80%;left:-45%;width:28%;height:260%;background:rgba(255,255,255,.46);transform:rotate(24deg);transition:left .7s ease}.btn:hover:after,.top-btn:hover:after{left:120%}.btn:hover,.top-btn:hover{transform:translateY(-2px);box-shadow:0 16px 36px rgba(215,173,96,.2)}
.hero{position:relative;overflow:hidden;padding:86px 0 72px;background:radial-gradient(circle at 78% 28%,rgba(215,173,96,.17),transparent 28%),linear-gradient(180deg,#111112,#0b0b0c)}.hero:after{content:'';position:absolute;right:-160px;bottom:-240px;width:760px;height:760px;border:1px solid rgba(215,173,96,.10);border-radius:50%;animation:spin 35s linear infinite}.hero-grid{display:grid;grid-template-columns:1.02fr .98fr;gap:68px;align-items:center;position:relative;z-index:2}.label{display:flex;align-items:center;gap:12px;color:var(--gold);text-transform:uppercase;letter-spacing:.19em;font-size:12px;font-weight:800}.label span{width:44px;height:1px;background:var(--gold)}
h1{font-size:clamp(62px,7.8vw,112px);line-height:.87;letter-spacing:-.055em;margin:22px 0 24px}.hero-kicker{font-family:Georgia,serif;font-size:27px;color:#e9dfd0;margin:0 0 18px}.hero-copy{font-size:20px;line-height:1.55;color:#c0b7aa;max-width:690px}.hero-actions{display:flex;gap:22px;align-items:center;flex-wrap:wrap;margin-top:32px}.price{font-family:Georgia,serif;font-size:44px;color:var(--gold);font-weight:700}.micro{font-size:13px;color:#8f897f;margin-top:11px}.by{margin-top:18px;color:#ddd4c6;font-size:13px;letter-spacing:.12em}.by b{color:var(--gold)}
.car-scene{min-height:560px;position:relative;display:grid;place-items:center;perspective:1200px}.car-glow{position:absolute;width:470px;height:470px;border-radius:50%;background:radial-gradient(circle,rgba(215,173,96,.28),rgba(215,173,96,.05) 45%,transparent 70%);filter:blur(8px);animation:glow 5s ease-in-out infinite}.suv{width:430px;height:230px;border-radius:48% 52% 28% 28%/55% 58% 30% 28%;background:linear-gradient(145deg,#363638,#111214);box-shadow:0 34px 60px rgba(0,0,0,.5),inset -25px -18px 50px rgba(255,255,255,.03);transform:rotateY(-14deg);position:relative;animation:carFloat 6s ease-in-out infinite}.suv:before,.suv:after{content:'';position:absolute;bottom:-28px;width:78px;height:78px;border-radius:50%;background:radial-gradient(circle,#232323 0 34%,#060606 35% 64%,#444 65% 69%,#0a0a0a 70%)}.suv:before{left:58px}.suv:after{right:60px}.windshield{position:absolute;left:118px;top:28px;width:190px;height:76px;border-radius:48% 52% 16% 16%;background:linear-gradient(160deg,#181d21,#48525a);border:1px solid #666}.lightbar{position:absolute;right:20px;top:123px;width:86px;height:10px;border-radius:20px;background:#d8b472;box-shadow:0 0 28px rgba(216,180,114,.7)}.groundline{position:absolute;bottom:92px;left:4%;right:0;height:1px;background:linear-gradient(90deg,transparent,var(--gold),transparent)}.hero-note{position:absolute;right:2%;bottom:20px;width:250px;color:#d7c69f;font-family:Georgia,serif;font-size:20px;line-height:1.3}
.metrics{border-top:1px solid #2d2923;border-bottom:1px solid #2d2923;background:#0d0d0e}.metrics-in{display:grid;grid-template-columns:repeat(4,1fr);gap:0}.metric{padding:22px;text-align:center;border-right:1px solid #2d2923;color:#bcb3a6}.metric:last-child{border-right:0}.metric b{display:block;color:var(--gold);font-family:Georgia,serif;font-size:22px;margin-bottom:4px}
section{padding:96px 0}.light{background:var(--cream);color:#171716}.paper{background:var(--paper);color:#171716}.dark2{background:#101011} h2{font-size:clamp(42px,5.2vw,74px);line-height:1.02;letter-spacing:-.035em;margin:16px 0 24px}.lead{font-size:19px;line-height:1.65;max-width:790px}.light .lead,.paper .lead{color:#5e594f}.dark2 .lead,.lead-dark{color:#aaa296}
.cards4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}.card{padding:26px;border:1px solid #ded5c6;background:#fff;position:relative;transition:.3s}.card.dark{background:#161617;border-color:#302b24;color:#f5efe4}.card:hover{transform:translateY(-7px);box-shadow:0 24px 45px rgba(0,0,0,.12)}.card-num{font-family:Georgia,serif;color:var(--gold);font-size:34px;margin-bottom:18px}.card h3{font-size:22px;margin:0 0 10px}.card p{margin:0;line-height:1.55;color:#655f56}.card.dark p{color:#aaa296}.tag{display:inline-block;margin-top:18px;font-size:11px;letter-spacing:.15em;color:#9b7336;font-weight:800}
.quote-line{margin-top:36px;padding-top:20px;border-top:1px solid #cfc4b3;font-family:Georgia,serif;font-size:24px;color:#3b342b}
.method-head{display:grid;grid-template-columns:1fr .9fr;gap:60px;align-items:end}.pill5p{justify-self:end;width:180px;height:180px;border-radius:50%;border:1px solid var(--gold);display:grid;place-items:center;text-align:center;background:radial-gradient(circle,rgba(215,173,96,.12),transparent 65%)}.pill5p b{font-family:Georgia,serif;font-size:56px;color:var(--gold)}.pill5p span{display:block;font-size:13px;color:#c2b9aa;line-height:1.35}.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-top:40px}.step{padding:22px 18px;border-top:2px solid var(--gold);background:#171718;min-height:205px;transition:.3s}.step:hover{transform:translateY(-7px);background:#1d1d1e}.step b{display:block;font-family:Georgia,serif;color:var(--gold);font-size:28px;margin-bottom:15px}.step h3{font-size:19px;margin:0 0 8px}.step p{margin:0;color:#aaa296;font-size:14px;line-height:1.5}
.garage-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:50px;align-items:start}.checklist{background:#111112;color:#f7f2e8;padding:34px;border-top:4px solid var(--gold);box-shadow:0 22px 55px rgba(35,25,10,.12)}.checklist h3{font-size:34px;margin:0 0 14px}.checks{display:grid;gap:14px;margin-top:22px}.check{display:flex;gap:12px;align-items:flex-start}.check i{font-style:normal;color:var(--gold);font-weight:900}.mini-tools{display:grid;gap:15px}.mini-tool{padding:22px;background:#fff;border:1px solid #ded5c6;display:grid;grid-template-columns:54px 1fr;gap:16px;align-items:start}.mini-tool .n{font-family:Georgia,serif;color:var(--gold);font-size:30px}.mini-tool h3{font-size:21px;margin:0 0 6px}.mini-tool p{margin:0;color:#655f56;line-height:1.5}
.previews{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:42px}.preview{background:#151516;border:1px solid #3a3328;padding:18px;min-height:340px;position:relative;overflow:hidden;transition:.35s}.preview:hover{transform:translateY(-8px);border-color:#776039}.preview-page{height:220px;background:linear-gradient(180deg,#f6efe3,#d9cfbf);color:#181716;padding:20px;position:relative;overflow:hidden}.preview-page:after{content:'';position:absolute;left:0;right:0;bottom:0;height:52%;background:linear-gradient(transparent,rgba(246,239,227,.98))}.preview-page.darkp{background:linear-gradient(180deg,#171718,#09090a);color:#f7f0e5}.preview-page.darkp:after{background:linear-gradient(transparent,rgba(9,9,10,.98))}.preview-title{font-family:Georgia,serif;font-size:22px;line-height:1.05}.preview-lines{margin-top:18px;display:grid;gap:8px}.preview-lines span{display:block;height:7px;background:#c7bba8}.darkp .preview-lines span{background:#3d382f}.preview-badge{position:absolute;left:16px;right:16px;bottom:16px;padding:10px;background:#111;color:#f2e7d6;border-top:2px solid var(--gold);z-index:2;font-size:12px}.preview h3{font-size:21px;margin:18px 0 7px}.preview p{margin:0;color:#9f978b;font-size:14px;line-height:1.5}
.three{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:38px}.scenario{padding:28px;background:#171718;border:1px solid #302b24}.scenario .k{color:var(--gold);font-size:11px;font-weight:900;letter-spacing:.16em}.scenario h3{font-size:24px;margin:12px 0}.scenario p{color:#aaa296;line-height:1.6;margin:0}
.author-grid{display:grid;grid-template-columns:.75fr 1.25fr;gap:60px;align-items:center}.author-art{height:380px;border:1px solid #d8cebd;background:radial-gradient(circle at 65% 30%,rgba(215,173,96,.18),transparent 34%),#111112;display:grid;place-items:center}.author-seal{width:150px;height:150px;border:1px solid var(--gold);border-radius:50%;display:grid;place-items:center;font-family:Georgia,serif;color:var(--gold);font-size:44px;animation:pulse 4s ease-in-out infinite}.signature{font-family:Georgia,serif;color:#91692f;font-size:24px;margin-top:22px}
.offer-wrap{background:linear-gradient(180deg,#f1e8d9,#e3d6c2);color:#171716}.offer{display:grid;grid-template-columns:.85fr 1.15fr;gap:44px;background:#111112;color:#f7f2e8;border:1px solid var(--gold);padding:46px;box-shadow:0 30px 70px rgba(47,32,8,.2)}.book-cover{height:480px;max-width:330px;margin:auto;background:linear-gradient(165deg,#171718,#070708);border:1px solid #725a32;padding:44px 30px;display:flex;flex-direction:column;box-shadow:0 28px 58px rgba(0,0,0,.45);animation:bookFloat 5.5s ease-in-out infinite}.book-cover small{color:var(--gold);letter-spacing:.16em;font-size:10px}.book-cover h3{font-size:46px;line-height:.94;margin:22px 0}.book-cover p{color:#bdb4a8;line-height:1.5}.book-cover .author-name{margin-top:auto;font-weight:800;letter-spacing:.08em}.offer h2{font-size:56px;margin-bottom:8px}.offer ul{list-style:none;padding:0;display:grid;gap:11px;margin:24px 0}.offer li:before{content:'✓';color:var(--gold);font-weight:900;margin-right:10px}.offer-price{font-family:Georgia,serif;color:var(--gold);font-size:64px;font-weight:700;line-height:1}.offer-micro{color:#9d958a;font-size:13px;margin:9px 0 25px}.pending{font-size:12px;color:#8f887d;margin-top:12px}.faq details{border-top:1px solid #302d27;padding:20px 0}.faq summary{cursor:pointer;font-weight:800}.faq summary:hover{color:var(--gold)}.faq p{color:#aaa296;line-height:1.6;max-width:840px}.final{text-align:center;background:radial-gradient(circle at 50% 10%,rgba(215,173,96,.08),transparent 35%),#09090a;padding:112px 0}.final h2{max-width:900px;margin:16px auto 22px}.final p{color:#aaa296}.footer{border-top:1px solid #28251f;padding:34px 0;color:#7f786f;font-size:12px}.footer-in{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.footer a{color:#9d958a;text-decoration:none}
.reveal{opacity:0;transform:translateY(30px);transition:opacity .75s cubic-bezier(.2,.7,.2,1),transform .75s cubic-bezier(.2,.7,.2,1)}.reveal.show{opacity:1;transform:none}
@keyframes spin{to{transform:rotate(360deg)}}@keyframes glow{0%,100%{opacity:.65;transform:scale(1)}50%{opacity:1;transform:scale(1.08)}}@keyframes carFloat{0%,100%{transform:rotateY(-14deg) translateY(0)}50%{transform:rotateY(-10deg) translateY(-12px)}}@keyframes bookFloat{0%,100%{transform:translateY(0) rotateY(-4deg)}50%{transform:translateY(-12px) rotateY(0)}}@keyframes pulse{0%,100%{box-shadow:0 0 0 0 rgba(215,173,96,0)}50%{box-shadow:0 0 0 16px rgba(215,173,96,.07)}}
@media(max-width:980px){.nav{display:none}.hero-grid,.garage-grid,.author-grid,.offer,.method-head{grid-template-columns:1fr}.car-scene{order:-1;min-height:420px}.cards4{grid-template-columns:1fr 1fr}.steps{grid-template-columns:1fr 1fr}.previews,.three{grid-template-columns:1fr}.metrics-in{grid-template-columns:1fr 1fr}.metric:nth-child(2){border-right:0}.pill5p{justify-self:start}.offer{padding:30px}}
@media(max-width:560px){.wrap{width:min(100% - 26px,1160px)}h1{font-size:58px}.cards4,.steps,.metrics-in{grid-template-columns:1fr}.metric{border-right:0;border-bottom:1px solid #2d2923}.suv{width:330px;height:185px}.car-scene{min-height:360px}.hero-note{display:none}.top-btn{font-size:11px;padding:10px 13px}.brand{font-size:15px}.offer-price{font-size:54px}.book-cover{height:420px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}.reveal{opacity:1;transform:none}}
`}</style>

<nav className="top"><div className="wrap top-in"><a className="brand" href="#topo"><span className="brand-mark">S</span><span>SEMINOVO <span className="gold">SEM SURPRESA</span></span></a><div className="nav"><a href="#metodo">O método</a><a href="#recebe">O que você recebe</a><a href="#dentro">Veja por dentro</a><a href="#duvidas">Dúvidas</a></div><a className="top-btn" href="#oferta">Conhecer o guia ↗</a></div></nav>

<header className="hero"><div className="wrap hero-grid">
  <div><Label>Guia do comprador inteligente</Label><h1>Antes do PIX,<br/><span className="gold">entenda o carro.</span></h1><p className="hero-kicker">O carro chamou sua atenção. Agora descubra o que merece a sua.</p><p className="hero-copy">55 páginas para saber o que perguntar, conferir o carro, comparar custos e negociar com fatos. Do primeiro anúncio à decisão antes do PIX.</p><div className="hero-actions"><a className="btn" href="#oferta">Quero comprar com mais segurança ↗</a><div><div className="price">R$ 39,90</div><div className="micro">pagamento único · guia digital</div></div></div><div className="by">POR <b>ARTHUR LONGOBUCO</b></div></div>
  <div className="car-scene"><div className="car-glow"/><div className="groundline"/><div className="suv"><div className="windshield"/><div className="lightbar"/></div><div className="hero-note">OLHE ALÉM DA APARÊNCIA.<br/>A boa compra começa nas perguntas certas.</div></div>
</div></header>

<div className="metrics"><div className="wrap metrics-in"><div className="metric"><b>55 páginas</b>20 capítulos</div><div className="metric"><b>5P</b>método de decisão</div><div className="metric"><b>0–100</b>nota da compra segura</div><div className="metric"><b>✓</b>checklist + ficha de campo</div></div></div>

<section className="light"><div className="wrap"><Reveal><Label>01 / O que está em jogo</Label><h2>Um bom preço.<br/>Mas é uma boa compra?</h2><p className="lead">Preço baixo, pouca quilometragem e aparência impecável chamam atenção. Mas nenhum deles, sozinho, conta a história inteira.</p></Reveal><div className="cards4"><Reveal delay={80}><div className="card"><div className="card-num">01</div><h3>O desconto que vira manutenção.</h3><p>Pneus, revisão e reparos próximos entram na conta. Mesmo quando não aparecem no anúncio.</p><span className="tag">CUSTO REAL</span></div></Reveal><Reveal delay={150}><div className="card"><div className="card-num">02</div><h3>Um passado que muda o valor.</h3><p>Quilometragem e procedência precisam fazer sentido juntas. O histórico merece uma segunda olhada.</p><span className="tag">PROCEDÊNCIA</span></div></Reveal><Reveal delay={220}><div className="card"><div className="card-num">03</div><h3>Laudo aprovado. E a mecânica?</h3><p>Entenda o que a cautelar verifica e quando chamar um profissional para uma avaliação mecânica.</p><span className="tag">AVALIAÇÃO</span></div></Reveal><Reveal delay={290}><div className="card"><div className="card-num">04</div><h3>A parcela cabe. E o custo total?</h3><p>Uma prestação menor não conta tudo. Compare o valor final antes de decidir pelo financiamento.</p><span className="tag">FINANCIAMENTO</span></div></Reveal></div><div className="quote-line">↳ Pagar barato é sobre preço. Comprar bem é sobre o conjunto.</div></div></section>

<section id="metodo"><div className="wrap"><div className="method-head"><Reveal><Label>02 / Da empolgação à decisão</Label><h2>Você não precisa virar mecânico.</h2><p className="lead-dark">Precisa saber o que perguntar, o que observar e em que momento pedir ajuda.</p></Reveal><div className="pill5p"><div><b>5P</b><span>Preço · Procedência · Produto · Papelada · Pagamento</span></div></div></div><div className="steps">{[['01','Escolha com intenção.','Defina o carro certo para sua rotina e seu orçamento antes de abrir os anúncios.'],['02','Investigue a história.','Preço, FIPE, quilometragem, procedência e documentos: conecte os pontos.'],['03','Olhe de perto.','Carroceria, pneus, interior, motor e test-drive. Saiba onde concentrar sua atenção.'],['04','Negocie com fatos.','Transforme observações e reparos conhecidos em argumentos e números.'],['05','Decida com método.','Reúna as informações no 5P, na Nota da Compra Segura e no checklist final.']].map(([n,t,d],i)=><Reveal delay={i*80} key={n}><div className="step"><b>{n}</b><h3>{t}</h3><p>{d}</p></div></Reveal>)}</div></div></section>

<section className="paper" id="recebe"><div className="wrap garage-grid"><Reveal><Label>03 / Do guia para a garagem</Label><h2>Leia antes da visita.<br/>Use diante do carro.</h2><p className="lead">Ferramentas práticas para consultar no celular durante a visita e comparar suas opções com calma, depois.</p><div className="checklist"><div className="tag" style={{color:'#d7ad60'}}>SEU ROTEIRO DE VERIFICAÇÃO</div><h3>Checklist Definitivo.</h3><p>Uma sequência organizada do que conferir antes de fechar negócio.</p><div className="checks"><div className="check"><i>✓</i><span>Histórico e documentação</span></div><div className="check"><i>✓</i><span>Condição e conservação</span></div><div className="check"><i>✓</i><span>Custos antes da decisão</span></div></div><div className="quote-line" style={{color:'#f6efe4',borderColor:'#3b342a',fontSize:18}}>CONFERIR ANTES. DECIDIR DEPOIS.</div></div></Reveal><div className="mini-tools"><Reveal delay={100}><div className="mini-tool"><div className="n">01</div><div><h3>Ficha de Campo</h3><p>Registre observações durante a visita. Sua memória não precisa guardar todos os detalhes.</p></div></div></Reveal><Reveal delay={180}><div className="mini-tool"><div className="n">02</div><div><h3>Método 5P</h3><p>Os cinco pilares para avaliar a compra como um todo, além do modelo e do preço.</p></div></div></Reveal><Reveal delay={260}><div className="mini-tool"><div className="n">03</div><div><h3>Nota da Compra Segura</h3><p>Uma escala de 0 a 100 para organizar critérios e comparar diferentes exemplares.</p></div></div></Reveal></div></div></section>

<section className="dark2" id="dentro"><div className="wrap"><Reveal><Label>Prévias reais do guia</Label><h2>Veja o que vai acompanhar sua compra.</h2><p className="lead-dark">Um guia visual para ler com calma e ferramentas para consultar na visita. Veja trechos do material. As ferramentas completas fazem parte do guia.</p></Reveal><div className="previews"><Reveal delay={80}><div className="preview"><div className="preview-page darkp"><div className="preview-title">Um olhar mais atento.</div><div className="preview-lines"><span/><span/><span/><span/></div><div className="preview-badge">Prévia do material · versão completa no guia</div></div><h3>O que observar antes do test-drive.</h3><p>Trecho da página de inspeção: como observar o carro de longe.</p></div></Reveal><Reveal delay={160}><div className="preview"><div className="preview-page"><div className="preview-title">Anote antes de decidir.</div><div className="preview-lines"><span/><span/><span/><span/></div><div className="preview-badge">Prévia do material · versão completa no guia</div></div><h3>Ficha de campo para imprimir e levar.</h3><p>Prévia parcial com título e primeiros campos.</p></div></Reveal><Reveal delay={240}><div className="preview"><div className="preview-page darkp"><div className="preview-title">Releia antes do PIX.</div><div className="preview-lines"><span/><span/><span/><span/></div><div className="preview-badge">Prévia do material · versão completa no guia</div></div><h3>Os 5P em 60 segundos.</h3><p>Também no guia: test-drive orientado, limites da cautelar, negociação com fatos, financiamento e pontuação de 0 a 100.</p></div></Reveal></div><div style={{marginTop:34}}><a className="btn" href="#oferta">Conhecer a oferta ↗</a></div></div></section>

<section><div className="wrap"><Reveal><Label>04 / Prepare sua próxima compra</Label><h2>Chegue à visita com perguntas.<br/>Saia com critérios.</h2><p className="lead-dark">Transforme a empolgação pelo carro em uma análise que você consegue organizar, comparar e usar na negociação.</p></Reveal><div className="three"><Reveal delay={80}><div className="scenario"><div className="k">NA VISITA</div><h3>A inspeção de 15 minutos.</h3><p>Comece pela pintura, alinhamento, pneus e interior. Um roteiro inicial para decidir se vale continuar investigando, sem substituir a avaliação profissional.</p></div></Reveal><Reveal delay={160}><div className="scenario"><div className="k">NA COMPARAÇÃO</div><h3>Seu usado também é dinheiro.</h3><p>Compare a diferença final na troca, os reparos e o que cada proposta inclui. Um desconto isolado não conta a história inteira.</p></div></Reveal><Reveal delay={240}><div className="scenario"><div className="k">NA DECISÃO</div><h3>Saiba quando ir embora.</h3><p>Reconheça histórias contraditórias, resistência à verificação e pressão para pagar. O tempo investido na pesquisa não obriga você a comprar.</p></div></Reveal></div><div style={{marginTop:32}}><a className="btn" href="#oferta">Quero me preparar para comprar ↗</a></div></div></section>

<section className="light"><div className="wrap author-grid"><Reveal><div className="author-art"><div className="author-seal">AL</div></div></Reveal><Reveal delay={120}><Label>05 / Sobre o autor</Label><h2>Arthur Longobuco.</h2><div className="tag">AUTOR DE SEMINOVO SEM SURPRESA</div><p className="lead">Fazer perguntas melhores antes de tomar uma decisão cara. Essa é a proposta de <em>Seminovo sem Surpresa</em>: transformar uma compra complexa em um processo mais claro, prático e organizado.</p><p className="lead">O guia reúne critérios de avaliação, comparação, documentação, negociação e decisão a partir de situações recorrentes do mercado e dúvidas que compradores enfrentam todos os dias.</p><div className="signature">Uma compra melhor começa com informação.</div></Reveal></div></section>

<section className="offer-wrap" id="oferta"><div className="wrap"><div className="offer"><div className="book-cover"><small>EDIÇÃO DIGITAL</small><h3>Seminovo<br/><span className="gold">sem Surpresa.</span></h3><p>O guia do comprador inteligente.</p><div className="author-name">ARTHUR LONGOBUCO</div></div><div><Label>O próximo passo é seu</Label><h2>Uma grande decisão.<br/>Um pequeno investimento.</h2><p style={{color:'#bdb5a8',fontSize:18,lineHeight:1.6}}>Antes de comprometer milhares de reais em um carro, invista R$ 39,90 em informação para avaliar suas opções com mais critério. Leia antes da visita. Consulte durante a avaliação. Compare antes de decidir.</p><ul><li>55 páginas com 20 capítulos ilustrados</li><li>Checklist Definitivo + Ficha de Campo</li><li>Método 5P da Compra Segura</li><li>Nota da Compra Segura de 0 a 100</li><li>Resumo visual: os 5P em 60 segundos</li><li>Inspeção, test-drive, troca e financiamento</li></ul><div className="offer-price">R$ 39,90</div><div className="offer-micro">Pagamento único · sem assinatura</div><a className="btn" href="#">Quero o guia por R$ 39,90 ↗</a><div className="pending">Vendas em preparação. Confira a disponibilidade.<br/>Para ler no celular, tablet ou computador.</div></div></div></div></section>

<section className="faq" id="duvidas"><div className="wrap"><Label>Sem letras miúdas</Label><h2>Antes de seguir.</h2><details open><summary>Não entendo de carro. O guia serve para mim?</summary><p>Sim. O conteúdo foi pensado para compradores comuns, com orientações sobre o que perguntar, observar e investigar, sem exigir conhecimento técnico.</p></details><details><summary>Substitui um mecânico ou laudo cautelar?</summary><p>Não. O guia ajuda você a saber o que observar e em que momento procurar avaliação profissional ou cautelar.</p></details><details><summary>Posso consultar durante a visita ao veículo?</summary><p>Sim. A Ficha de Campo, o Checklist e os resumos foram pensados para acompanhar a visita ao carro.</p></details><details><summary>Serve para comprar em loja e de particular?</summary><p>Sim. O conteúdo ajuda a organizar a decisão nos dois cenários.</p></details><details><summary>Como recebo o guia?</summary><p>O acesso será digital e poderá ser usado no celular, tablet ou computador após a confirmação do pagamento.</p></details></div></section>

<section className="final"><div className="wrap"><Label>Guarde esta ideia</Label><h2>Não é só o modelo.<br/><span className="gold">É aquele exemplar.</span></h2><p>Investigue. Compare. Faça as contas. E só depois decida.</p><div style={{marginTop:28}}><a className="btn" href="#oferta">Comece pelo guia ↗</a></div></div></section>

<footer className="footer"><div className="wrap footer-in"><div><b>SEMINOVO SEM SURPRESA</b><br/>Uma compra melhor começa com informação.</div><div><a href="#topo">Voltar ao início ↑</a></div><div>© 2026 · Seminovo sem Surpresa · Arthur Longobuco<br/>Material educacional. Não substitui avaliação técnica, mecânica, documental ou jurídica profissional.</div></div></footer>
</div>;
}
