import React, { useEffect, useRef, useState } from 'react';

const testimonials = [
  ['Marcos Almeida','42 anos • Campinas/SP • personagem fictício','Eu sempre olhava primeiro a quilometragem. Depois do guia, comecei a comparar histórico, manutenção e custo futuro. A compra ficou muito mais racional.'],
  ['Juliana Ribeiro','35 anos • Curitiba/PR • personagem fictício','A inspeção de 15 minutos foi a parte que mais usei. Fui ver o carro com a ficha aberta no celular e percebi pontos que normalmente eu teria ignorado.'],
  ['Renato Campos','47 anos • Belo Horizonte/MG • personagem fictício','Eu achava que cautelar aprovada significava que motor e câmbio estavam perfeitos. Só essa explicação já mudou totalmente minha forma de avaliar um carro.'],
  ['Fernanda Lopes','39 anos • Ribeirão Preto/SP • personagem fictício','Usei o Método 5P para comparar dois carros. O mais barato perdeu em procedência e custo futuro. O método me ajudou a decidir com muito mais calma.'],
];

const Reveal = ({children, delay=0, className=''}:{children:React.ReactNode;delay?:number;className?:string}) => {
  const ref = useRef<HTMLDivElement>(null);
  const [show,setShow] = useState(false);
  useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShow(true);io.disconnect();}},{threshold:.14});io.observe(el);return()=>io.disconnect();},[]);
  return <div ref={ref} className={`reveal ${show?'show':''} ${className}`} style={{transitionDelay:`${delay}ms`}}>{children}</div>
}

const Label=({children}:{children:React.ReactNode})=><div className="label"><span/>{children}</div>;

export default function App(){
return <div className="site">
<style>{`
:root{--ink:#0b0b0c;--ink2:#121213;--cream:#f2ecdf;--paper:#faf7f1;--gold:#d7ad60;--gold2:#b88639;--muted:#b8b0a4;--line:#302d27}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--ink);color:#f6f1e8;font-family:Inter,Arial,sans-serif;overflow-x:hidden}.site{min-height:100vh}.wrap{width:min(1160px,calc(100% - 40px));margin:auto}
h1,h2,h3,.serif{font-family:Georgia,'Times New Roman',serif}.g{color:var(--gold)}
.top{position:sticky;top:0;z-index:50;background:rgba(11,11,12,.78);backdrop-filter:blur(18px);border-bottom:1px solid rgba(215,173,96,.12)}.top-in{height:68px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-family:Georgia,serif;font-weight:700;font-size:20px}.brand b{color:var(--gold)}
.btn,.top-btn{position:relative;overflow:hidden;background:linear-gradient(180deg,#e3bf78,#c69647);color:#111;text-decoration:none;font-weight:900;border-radius:9px;display:inline-flex;align-items:center;justify-content:center;transition:.28s ease;box-shadow:0 10px 30px rgba(215,173,96,.12)}.btn{padding:17px 25px}.top-btn{padding:11px 17px;font-size:14px}.btn:after,.top-btn:after{content:'';position:absolute;top:-80%;left:-45%;width:30%;height:260%;background:rgba(255,255,255,.5);transform:rotate(24deg);transition:left .65s ease}.btn:hover:after,.top-btn:hover:after{left:120%}.btn:hover,.top-btn:hover{transform:translateY(-3px);box-shadow:0 15px 34px rgba(215,173,96,.2)}
.hero{position:relative;overflow:hidden;padding:88px 0 82px;background:radial-gradient(circle at 78% 28%,rgba(215,173,96,.18),transparent 30%),linear-gradient(180deg,#111112 0%,#0b0b0c 100%)}.hero:before{content:'';position:absolute;width:680px;height:680px;border-radius:50%;right:-250px;top:-180px;border:1px solid rgba(215,173,96,.14);animation:spin 28s linear infinite}.hero:after{content:'';position:absolute;inset:auto -10% -220px auto;width:900px;height:420px;background:radial-gradient(circle,rgba(215,173,96,.08),transparent 65%);animation:glow 6s ease-in-out infinite}
.hero-grid{display:grid;grid-template-columns:1.02fr .98fr;gap:64px;align-items:center;position:relative;z-index:2}.label{display:flex;align-items:center;gap:12px;color:var(--gold);text-transform:uppercase;letter-spacing:.2em;font-size:12px;font-weight:800}.label span{width:46px;height:1px;background:var(--gold);transform-origin:left;animation:lineGrow 1s ease both}
h1{font-size:clamp(58px,7.8vw,112px);line-height:.86;letter-spacing:-.055em;margin:24px 0 28px}.hero-copy{font-size:21px;line-height:1.55;color:#c1b9ac;max-width:690px}.author{margin-top:20px;font-weight:700}.author b{color:var(--gold)}.hero-actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap;margin-top:34px}.price{font-family:Georgia,serif;color:var(--gold);font-size:46px;font-weight:700;line-height:1}.micro{font-size:13px;color:#8f897f;margin-top:12px}
.book-stage{min-height:610px;display:grid;place-items:center;position:relative;perspective:1400px}.book{width:340px;height:500px;background:linear-gradient(165deg,#171718,#070708);border:1px solid #6b542d;box-shadow:-28px 34px 70px rgba(0,0,0,.5),inset 10px 0 28px rgba(255,255,255,.025);transform:rotateY(-12deg) rotateZ(2deg);position:relative;padding:54px 34px;display:flex;flex-direction:column;z-index:3;animation:bookFloat 5.5s ease-in-out infinite}.book:before{content:'';position:absolute;left:0;top:0;bottom:0;width:12px;background:linear-gradient(90deg,#080809,#282218,#080809)}.book small{color:var(--gold);letter-spacing:.18em;text-transform:uppercase;font-weight:800;font-size:10px}.book h3{font-size:48px;line-height:.92;margin:20px 0 18px}.book p{color:#c8c0b5;font-size:14px;line-height:1.45}.book-author{margin-top:auto;color:#e0d8ca;font-weight:700;font-size:14px}.road{height:3px;background:linear-gradient(90deg,transparent,var(--gold),transparent);position:absolute;left:34px;right:34px;bottom:38px;animation:pulseLine 2.6s ease-in-out infinite}.sheet{position:absolute;width:290px;height:410px;background:var(--cream);border:1px solid #baa676;box-shadow:0 20px 44px rgba(0,0,0,.32);padding:30px;color:#191817;transition:.4s ease}.s1{left:1%;transform:rotate(-8deg);animation:sheetL 6s ease-in-out infinite}.s2{right:0;transform:rotate(9deg);animation:sheetR 6.4s ease-in-out infinite}.sheet .n{font-family:Georgia,serif;font-size:64px;color:var(--gold);line-height:.8}.sheet h4{font-family:Georgia,serif;font-size:27px;margin:16px 0}.sheet .line{height:8px;background:#d7d0c2;margin:10px 0}.sheet .short{width:65%}.sheet .box{margin-top:22px;background:#111;color:#eee;padding:16px;border-top:3px solid var(--gold);font-size:12px}
.trust{border-top:1px solid #2e2b26;border-bottom:1px solid #2e2b26;background:#0d0d0e}.trust-in{display:flex;justify-content:center;gap:38px;flex-wrap:wrap;padding:19px 0;color:#aaa297;font-size:14px}.trust-in span{transition:.25s}.trust-in span:hover{color:var(--gold);transform:translateY(-2px)}
section{padding:96px 0}.light{background:var(--cream);color:#171716}.paper{background:var(--paper);color:#171716}.dark2{background:#111112}h2{font-size:clamp(42px,5vw,72px);line-height:1.02;letter-spacing:-.035em;margin:18px 0 24px}.lead{font-size:19px;line-height:1.65;color:#615b52;max-width:780px}.lead-dark{font-size:18px;line-height:1.65;color:#aaa296;max-width:800px}
.problems{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-top:42px}.problem,.tool,.test{transition:transform .32s ease,box-shadow .32s ease,border-color .32s ease}.problem{background:#fff;border-top:3px solid var(--gold);padding:24px}.problem:hover{transform:translateY(-8px);box-shadow:0 20px 35px rgba(40,29,10,.12)}.problem strong{display:block;font-family:Georgia,serif;font-size:19px;margin-bottom:8px}
.method{display:grid;grid-template-columns:.88fr 1.12fr;gap:72px;align-items:start}.row{display:grid;grid-template-columns:62px 1fr;gap:20px;border-bottom:1px solid #302d27;padding:22px 0;transition:.3s}.row:hover{padding-left:10px;border-color:var(--gold)}.num{font-family:Georgia,serif;color:var(--gold);font-size:34px}.row h3{font-size:22px;margin:0 0 5px}.row p{margin:0;color:#aaa296;line-height:1.55}
.tools{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;margin-top:38px}.tool{background:#fff;border:1px solid #ded4c4;padding:28px;position:relative}.tool:before{content:'';position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--gold)}.tool:hover{transform:translateY(-7px) scale(1.01);box-shadow:0 22px 45px rgba(42,31,12,.12)}.tool h3{margin:0 0 8px;font-size:25px}.tool p{margin:0;color:#655f57}
.test-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:36px}.test{background:linear-gradient(145deg,#19191a,#111112);border:1px solid #3a3428;padding:26px;min-height:250px}.test:hover{transform:translateY(-7px);border-color:#7d673d;box-shadow:0 22px 50px rgba(0,0,0,.28)}.stars{color:var(--gold);letter-spacing:.12em;margin-bottom:14px}.test blockquote{font-family:Georgia,serif;font-size:19px;line-height:1.48;margin:0 0 22px;color:#f4eee5}.who{border-top:1px solid #302d27;padding-top:14px;color:var(--gold);font-weight:800}.who small{display:block;color:#817a71;font-weight:400;margin-top:5px}
.author-grid{display:grid;grid-template-columns:.72fr 1.28fr;gap:60px;align-items:center}.seal-card{height:360px;background:radial-gradient(circle at 70% 25%,rgba(215,173,96,.18),transparent 32%),#111112;border:1px solid #d8cebc;display:grid;place-items:center;overflow:hidden}.seal{width:142px;height:142px;border:1px solid var(--gold);border-radius:50%;display:grid;place-items:center;font-family:Georgia,serif;color:var(--gold);font-size:48px;animation:sealPulse 4s ease-in-out infinite}.signature{font-family:Georgia,serif;color:#936b2f;font-size:23px;margin-top:25px}
.value{position:relative;overflow:hidden}.value:after{content:'R$ 39,90';position:absolute;right:-40px;top:20px;font-family:Georgia,serif;font-size:145px;color:rgba(215,173,96,.045);font-weight:700;animation:drift 10s ease-in-out infinite}.quote{font-family:Georgia,serif;font-size:clamp(34px,4.5vw,66px);line-height:1.1;max-width:1000px;position:relative;z-index:2}
.offer-bg{background:linear-gradient(180deg,#f2ecdf,#e6dccb);color:#171716}.offer{background:#111112;color:#f7f2e8;border:1px solid var(--gold);display:grid;grid-template-columns:.8fr 1.2fr;gap:46px;padding:46px;box-shadow:0 28px 60px rgba(43,30,10,.2);transition:.35s}.offer:hover{box-shadow:0 35px 75px rgba(63,44,12,.26)}.mini-cover{height:450px;max-width:310px;margin:auto;background:#0c0c0d;border:1px solid #5d4928;box-shadow:0 25px 55px rgba(0,0,0,.42);padding:44px 30px;display:flex;flex-direction:column;animation:miniFloat 5s ease-in-out infinite}.mini-cover small{color:var(--gold);letter-spacing:.14em;font-size:9px}.mini-cover h3{font-size:42px;line-height:.95;margin:18px 0}.mini-cover p{font-size:13px;color:#bfb7aa}.ma{margin-top:auto;font-weight:700}.offer ul{padding:0;list-style:none;display:grid;gap:11px;margin:26px 0}.offer li:before{content:'✓';color:var(--gold);font-weight:900;margin-right:10px}.pay{display:flex;align-items:end;gap:13px;margin:26px 0}.once{color:#918a80;margin-bottom:8px}.faq details{border-top:1px solid #302d27;padding:21px 0}.faq summary{font-weight:800;cursor:pointer;transition:.25s}.faq summary:hover{color:var(--gold)}.faq p{color:#aca499;line-height:1.6;max-width:850px}.final{text-align:center;padding:110px 0;background:radial-gradient(circle at 50% 20%,rgba(215,173,96,.08),transparent 38%),#09090a}.final h2{max-width:940px;margin:18px auto 24px}.final p{color:#aaa296;margin-bottom:28px}footer{border-top:1px solid #28251f;text-align:center;color:#7e786f;font-size:12px;padding:35px 20px}
.reveal{opacity:0;transform:translateY(34px);transition:opacity .75s cubic-bezier(.2,.7,.2,1),transform .75s cubic-bezier(.2,.7,.2,1)}.reveal.show{opacity:1;transform:none}
@keyframes bookFloat{0%,100%{transform:rotateY(-12deg) rotateZ(2deg) translateY(0)}50%{transform:rotateY(-8deg) rotateZ(1deg) translateY(-16px)}}@keyframes sheetL{0%,100%{transform:rotate(-8deg) translateY(0)}50%{transform:rotate(-6deg) translateY(-8px)}}@keyframes sheetR{0%,100%{transform:rotate(9deg) translateY(0)}50%{transform:rotate(7deg) translateY(9px)}}@keyframes glow{0%,100%{opacity:.55;transform:scale(1)}50%{opacity:1;transform:scale(1.08)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulseLine{0%,100%{opacity:.55}50%{opacity:1;box-shadow:0 0 18px rgba(215,173,96,.45)}}@keyframes lineGrow{from{transform:scaleX(0)}to{transform:scaleX(1)}}@keyframes sealPulse{0%,100%{box-shadow:0 0 0 rgba(215,173,96,0)}50%{box-shadow:0 0 34px rgba(215,173,96,.18)}}@keyframes drift{0%,100%{transform:translateX(0)}50%{transform:translateX(-25px)}}@keyframes miniFloat{0%,100%{transform:translateY(0) rotate(-1deg)}50%{transform:translateY(-10px) rotate(1deg)}}
@media(max-width:900px){.hero-grid,.method,.author-grid,.offer{grid-template-columns:1fr}.book-stage{order:-1;min-height:500px}.problems{grid-template-columns:1fr 1fr}.tools,.test-grid{grid-template-columns:1fr}.sheet{display:none}.book{width:300px;height:445px}.hero{padding-top:54px}}@media(max-width:560px){.wrap{width:min(100% - 26px,1160px)}.problems{grid-template-columns:1fr}.top .brand{font-size:16px}.top-btn{font-size:12px;padding:9px 12px}h1{font-size:58px}.offer{padding:24px}.hero-copy{font-size:18px}.price{font-size:40px}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.reveal{opacity:1;transform:none}}
`}</style>
<nav className="top"><div className="wrap top-in"><div className="brand">Seminovo <b>sem Surpresa</b></div><a className="top-btn" href="#comprar">Comprar por R$ 39,90</a></div></nav>
<header className="hero"><div className="wrap hero-grid"><Reveal><Label>Guia do comprador inteligente</Label><h1>Antes do PIX,<br/><span className="g">entenda o carro.</span></h1><p className="hero-copy">Um guia visual e prático para escolher, investigar, avaliar, negociar e comprar um seminovo com muito mais clareza.</p><div className="author">por <b>Arthur Longobuco</b></div><div className="hero-actions"><div className="price">R$ 39,90</div><a className="btn" href="#comprar">QUERO COMPRAR COM MAIS SEGURANÇA</a></div><div className="micro">Acesso digital • leia no celular, tablet ou computador</div></Reveal><Reveal delay={180}><div className="book-stage"><div className="sheet s1"><div className="n">5P</div><h4>Método da compra segura</h4><div className="line"/><div className="line"/><div className="line short"/><div className="box">PREÇO • PROCEDÊNCIA • PRODUTO • PAPELADA • PAGAMENTO</div></div><div className="sheet s2"><div className="n">100</div><h4>Nota da Compra Segura</h4><div className="line"/><div className="line short"/><div className="line"/><div className="box">Compare diferentes carros com método.</div></div><div className="book"><small>Guia do comprador inteligente</small><h3>Seminovo<br/><span className="g">sem Surpresa</span></h3><p>O guia prático para escolher, avaliar, negociar e comprar um carro seminovo com segurança.</p><div className="book-author">Arthur Longobuco</div><div className="road"/></div></div></Reveal></div></header>
<div className="trust"><div className="wrap trust-in"><span>20 capítulos</span><span>Checklist definitivo</span><span>Ficha de campo</span><span>Método 5P</span><span>Nota 0–100</span></div></div>
<section className="light"><div className="wrap"><Reveal><Label>O risco não está no seminovo</Label><h2>Está no que você não conferiu antes.</h2><p className="lead">Preço baixo, pouca quilometragem e aparência impecável podem ser ótimos sinais. Mas nenhum deles, sozinho, prova que você encontrou um bom negócio.</p></Reveal><div className="problems">{[['Pneus e revisão','Custos próximos que somem do “desconto”.'],['Histórico','Procedência mal compreendida muda valor e risco.'],['Cautelar','Aprovada não significa mecânica perfeita.'],['Financiamento','Parcela menor pode esconder custo total maior.']].map((x,i)=><Reveal delay={i*90} key={x[0]}><div className="problem"><strong>{x[0]}</strong>{x[1]}</div></Reveal>)}</div></div></section>
<section><div className="wrap method"><Reveal><Label>Sem mecaniquês</Label><h2>Você não precisa virar mecânico.</h2><p className="lead-dark">Precisa saber o que perguntar, o que observar, o que investigar e em que momento chamar um profissional.</p></Reveal><div>{[['01','Escolha','Defina o carro certo para sua vida antes de abrir os anúncios.'],['02','Investigue','Preço, FIPE, quilometragem, histórico e documentação.'],['03','Inspecione','Carroceria, pneus, interior, motor e test-drive.'],['04','Negocie','Transforme fatos e reparos conhecidos em números.'],['05','Decida','Use o 5P, a Nota da Compra Segura e o checklist final.']].map((x,i)=><Reveal delay={i*80} key={x[0]}><div className="row"><div className="num">{x[0]}</div><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div></Reveal>)}</div></div></section>
<section className="paper"><div className="wrap"><Reveal><Label>Ferramentas que saem do papel</Label><h2>Abra o guia enquanto estiver olhando o carro.</h2></Reveal><div className="tools">{[['Checklist Definitivo','Organiza o que precisa ser verificado antes de fechar negócio.'],['Ficha de Campo','Anote observações na visita sem confiar apenas na memória.'],['Método 5P','Preço, Procedência, Produto, Papelada e Pagamento.'],['Nota da Compra Segura','Compare diferentes carros em uma escala de 0 a 100.']].map((x,i)=><Reveal delay={i*90} key={x[0]}><div className="tool"><h3>{x[0]}</h3><p>{x[1]}</p></div></Reveal>)}</div></div></section>
<section className="dark2"><div className="wrap"><Reveal><Label>Experiências ilustrativas</Label><h2>Como o guia pode mudar a forma de olhar um seminovo.</h2></Reveal><div className="test-grid">{testimonials.map((t,i)=><Reveal delay={i*90} key={t[0]}><div className="test"><div className="stars">★★★★★</div><blockquote>“{t[2]}”</blockquote><div className="who">{t[0]}<small>{t[1]}</small></div></div></Reveal>)}</div></div></section>
<section className="light"><div className="wrap author-grid"><Reveal><div className="seal-card"><div className="seal">AL</div></div></Reveal><Reveal delay={140}><Label>Sobre o autor</Label><h2>Arthur Longobuco</h2><p className="lead">Arthur Longobuco é autor de <em>Seminovo sem Surpresa</em>, um guia criado para transformar uma compra complexa em um processo mais claro, prático e organizado.</p><p className="lead">O conteúdo reúne critérios de avaliação, comparação, documentação, negociação e decisão, desenvolvidos a partir de situações recorrentes do mercado automotivo e de problemas que compradores enfrentam todos os dias.</p><div className="signature">A proposta é simples: fazer perguntas melhores antes de tomar uma decisão cara.</div></Reveal></div></section>
<section className="value"><div className="wrap"><Reveal><Label>Pense na proporção</Label><div className="quote">Um guia de <b className="g">R$ 39,90</b> para ajudar numa decisão que pode envolver <b className="g">R$ 50 mil, R$ 80 mil ou R$ 120 mil.</b></div><p className="lead-dark" style={{marginTop:28}}>R$ 39,90 não compra certeza. Compra informação para você decidir melhor.</p></Reveal></div></section>
<section className="offer-bg" id="comprar"><div className="wrap"><Reveal><div className="offer"><div className="mini-cover"><small>Guia do comprador inteligente</small><h3>Seminovo<br/><span className="g">sem Surpresa</span></h3><p>Escolha, avalie, negocie e compre com mais segurança.</p><div className="ma">Arthur Longobuco</div></div><div><Label>Acesso digital</Label><h2>Seminovo<br/><span className="g">sem Surpresa</span></h2><p style={{color:'#bcb4a6',fontSize:17}}>O guia completo para comprar um seminovo com método, e não apenas com entusiasmo.</p><ul><li>20 capítulos ilustrados</li><li>Checklist Definitivo</li><li>Ficha de Campo</li><li>Método 5P da Compra Segura</li><li>Nota da Compra Segura 0–100</li><li>FIPE, quilometragem, cautelar, test-drive, negociação e financiamento</li></ul><div className="pay"><div className="price">R$ 39,90</div><div className="once">pagamento único</div></div><a className="btn" href="#">COMPRAR AGORA</a><div className="micro">O botão será conectado ao checkout assim que cadastrarmos o produto.</div></div></div></Reveal></div></section>
<section className="faq"><div className="wrap"><Reveal><Label>Sem letras miúdas</Label><h2>Perguntas frequentes</h2></Reveal>{[['Eu não entendo nada de carro. Serve para mim?','Sim. O guia foi escrito para compradores comuns e mostra o que observar sem fingir que o leitor virou mecânico ou perito.'],['Substitui mecânico ou laudo cautelar?','Não. O guia mostra onde termina a observação do comprador e quando uma avaliação especializada é necessária.'],['Posso usar durante a visita ao veículo?','Sim. A Ficha de Campo, o Checklist e a Nota da Compra Segura foram pensados justamente para esse momento.'],['Serve para loja e particular?','Sim. O livro aborda os dois cenários e explica diferenças importantes.'],['Como recebo?','Após a confirmação do pagamento, o acesso digital será liberado pela plataforma de venda.']].map((x,i)=><Reveal delay={i*60} key={x[0]}><details open={i===0}><summary>{x[0]}</summary><p>{x[1]}</p></details></Reveal>)}</div></section>
<section className="final"><div className="wrap"><Reveal><Label>A regra final</Label><h2>Você não está comprando apenas um modelo.<br/><span className="g">Está comprando aquele exemplar.</span></h2><p>Investigue. Compare. Faça as contas. E só depois decida.</p><a className="btn" href="#comprar">QUERO O SEMINOVO SEM SURPRESA</a></Reveal></div></section>
<footer>Seminovo sem Surpresa • Arthur Longobuco<br/>Material educacional. Não substitui avaliação técnica, mecânica, documental ou jurídica profissional.</footer>
</div>
}
